<a href="https://colab.research.google.com/github/kalc1/CIT-99-Machine-Learning/blob/main/Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 2 Assignment
Enter your name in the cell below as a comment.
Add as many code cells as is required for the questions in the Exercises in Week 2 Assignment.

In [23]:
# Kevin Alcocer

In [24]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Exercise #1
Add the number of code cells and comment the code for the problems.  Make sure you enter the answers in the assignment and code here as well.

In [ ]:
list(range(6))

[0, 1, 2, 3, 4, 5]

# Exercise #2


In [ ]:
for number in range(4):
    print(3*number)

0
3
6
9


In [ ]:
  print(range(4))

range(0, 4)


In [ ]:
a_list = [3,8,13,18,23]

for x in a_list:
  print(2*x)

6
16
26
36
46


In [ ]:
for number in [0, 1, 2, 3]:
  print(3*number)

0
3
6
9


# Exercise #3

In [ ]:
[num**3 for num in range(7)]

[0, 1, 8, 27, 64, 125, 216]

In [ ]:
p_list = ['Bruno','Terrence','Erin','Neel','Alo','Ashley','Althea','Salvador']

[name for name in p_list if name not in ['Althea']] + ['Alo']

['Bruno', 'Terrence', 'Erin', 'Neel', 'Alo', 'Ashley', 'Salvador', 'Alo']

# Exercise #4

In [ ]:
L1 = (41, 58, 18, 82, 25, 71, 64, 29)
print(type(L1))

<class 'tuple'>


In [ ]:
L1[2]

18

In [ ]:
L1[1:8]

(58, 18, 82, 25, 71, 64, 29)

In [ ]:
L1[5:]

(71, 64, 29)

In [ ]:
L1[0:2]

(41, 58)

# Exercise #5

In [29]:
import numpy as np
a_list = [43,105,74,101,34,54]
n_array = np.array(a_list)
n_array

array([ 43, 105,  74, 101,  34,  54])

In [34]:
[49,25,52,17,33]

a1 = np.array([49,25,52,17,33])

a2 = np.array([25,54,13,92,76])

a1 - a2

array([ 24, -29,  39, -75, -43])

In [31]:
 b1 = np.array([35,28,3,11,6,12,11,17,28,16])
 b1[:8]

array([35, 28,  3, 11,  6, 12, 11, 17])

# Exercise #6

In [38]:
import pandas as pd
v1 = ['Hunter', 'Logan', 'Jett', 'Avery', 'Royal', 'Ryan']
v2 = ['Langtree', 'Logan', 'Jett', 'Avery', 'Royal', 'Ryan']
v3 = [53, 33, 31, 39, 53, 55]
v4 = [66766, 74638, 44545, 54610, 68509, 69531]
v5 = [22322, 6104, 11694, 6104, 9556, 6438]
dic = {'FirstName': v1, 'LastName': v2, 'Age':v3, 'Salary':v4, 'Bonus':v5}
df = pd.DataFrame(dic)
df

FirstName  LastName  Age  Salary  Bonus
0    Hunter  Langtree   53   66766  22322
1     Logan     Logan   33   74638   6104
2      Jett      Jett   31   44545  11694
3     Avery     Avery   39   54610   6104
4     Royal     Royal   53   68509   9556
5      Ryan      Ryan   55   69531   6438

# Exercise #7

In [40]:
import pandas as pd
v1 = ['Angel', 'Emery', 'Wren', 'River', 'Rowan', 'Cameron']
v2 = ['Vicary', 'Odom', 'Langtree', 'Ackehurst', 'Wadey', 'Odom']
v3 = [39, 59, 26, 25, 53, 52]
v4 = [36582, 57036, 47991, 46922, 51225, 78812]
v5 = [23742, 23664, 17506, 23726, 16239, 19848]
dic = {'FirstName': v1, 'LastName': v2, 'Age':v3, 'Salary':v4, 'Bonus':v5}
df = pd.DataFrame(dic)
df

FirstName   LastName  Age  Salary  Bonus
0     Angel     Vicary   39   36582  23742
1     Emery       Odom   59   57036  23664
2      Wren   Langtree   26   47991  17506
3     River  Ackehurst   25   46922  23726
4     Rowan      Wadey   53   51225  16239
5   Cameron       Odom   52   78812  19848

In [43]:
# b display the mean of the Salary column
df["Salary"].mean()

53094.666666666664

In [44]:
# c display all records where the salary is greater than the mean
df[df["Salary"]>df["Salary"].mean()]

FirstName LastName  Age  Salary  Bonus
1     Emery     Odom   59   57036  23664
5   Cameron     Odom   52   78812  19848

In [47]:
# f list the Salary values with index 0 to 3
df.loc[:3, "Salary"]

0    36582
1    57036
2    47991
3    46922
Name: Salary, dtype: int64

In [49]:
# e list the salary values for index 3 to end
df.loc[3:, "Salary"]

3    46922
4    51225
5    78812
Name: Salary, dtype: int64

In [51]:
# g list records 0 to 3 of the dataframe
df.loc[:3]

FirstName   LastName  Age  Salary  Bonus
0     Angel     Vicary   39   36582  23742
1     Emery       Odom   59   57036  23664
2      Wren   Langtree   26   47991  17506
3     River  Ackehurst   25   46922  23726

In [52]:
# d list records 0 to 2 of the dataframe
df.iloc[:3]

FirstName  LastName  Age  Salary  Bonus
0     Angel    Vicary   39   36582  23742
1     Emery      Odom   59   57036  23664
2      Wren  Langtree   26   47991  17506

In [54]:
# a display the index 0 to 2 of the bonus column
df.iloc[:3,4]

0    23742
1    23664
2    17506
Name: Bonus, dtype: int64

# Exercise #8